### ISSUE TITLE
keyWindow returns nil

### ISSUE THREAD

**Issue by tbrannam** [matthewmayer/MMLaunchImage#2]
In - (UIImage*)launchImage
is is possible to get the wrong size since the main window may not be made Key yet.
perhaps a fallback to the first UIWindow in sharedApplication.windows would be appropriate?

NSStringFromCGSize([UIApplication sharedApplication].keyWindow.bounds.size) ];

UIWindow *mainWindow = [UIApplication sharedApplication].keyWindow;
if (mainWindow == nil) {
   mainWindow = [[UIApplication sharedApplication].windows firstObject];
}

**Comment by matthewmayer** [comment]
thanks, merged PR!
